language: crystal

sudo: required
services:
  - docker

matrix:
  include:
    - install: # Clang 4.0 on Ubuntu 16.04 (Xenial)
      - docker build . -f Dockerfile.ubuntu -t bindgen-test --build-arg CLANG_VERSION=4.0
    - install: # Clang 5.0 on Ubuntu 16.04 (Xenial)
      - docker build . -f Dockerfile.ubuntu -t bindgen-test --build-arg CLANG_VERSION=5.0
    - install: # Clang "latest" on ArchLinux (Rolling)
      - docker build . -f Dockerfile.archlinux -t bindgen-test

script:
  - docker run --rm bindgen-test crystal spec
